# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: AWS-cli
  env: 
  AWS_CLI_AUTO_PROMPT=on-partial
  cd /workspace
    before:
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    cd $ THEIA_WORKSPACE_ROOT

    gp  env export AWS_ACCESS_KEY_ID=AKIAQVA7IN3FAI4IXNV3
    gp env export AWS_SECRET_ACCESS_KEY=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
    gp env export AWS_REGION=us-east-2